"""
Countries supported by Home Assistant: ISO codes and names (en, uk).

Generated with pycountry (ISO 3166-1 and its Ukrainian translation),
with short common names where the official ones are long or misleading.
"""

from typing import Final, NamedTuple


class Country(NamedTuple):
    """ISO 3166-1 alpha-3 code and names."""

    iso3: str
    en: str
    uk: str


# Excluded on principle: aggressor states in Russia's war against Ukraine.
EXCLUDED_COUNTRIES: Final = frozenset({"BY", "RU"})

COUNTRIES: Final[dict[str, Country]] = {
    "AD": Country("AND", "Andorra", "Андорра"),
    "AE": Country("ARE", "United Arab Emirates", "Об’єднані Арабські Емірати"),
    "AF": Country("AFG", "Afghanistan", "Афганістан"),
    "AG": Country("ATG", "Antigua and Barbuda", "Антигуа і Барбуда"),
    "AI": Country("AIA", "Anguilla", "Ангілья"),
    "AL": Country("ALB", "Albania", "Албанія"),
    "AM": Country("ARM", "Armenia", "Вірменія"),
    "AO": Country("AGO", "Angola", "Ангола"),
    "AQ": Country("ATA", "Antarctica", "Антарктида"),
    "AR": Country("ARG", "Argentina", "Аргентина"),
    "AS": Country("ASM", "American Samoa", "Американське Самоа"),
    "AT": Country("AUT", "Austria", "Австрія"),
    "AU": Country("AUS", "Australia", "Австралія"),
    "AW": Country("ABW", "Aruba", "Аруба"),
    "AX": Country("ALA", "Åland Islands", "Аландські острови"),
    "AZ": Country("AZE", "Azerbaijan", "Азербайджан"),
    "BA": Country("BIH", "Bosnia and Herzegovina", "Боснія і Герцеговина"),
    "BB": Country("BRB", "Barbados", "Барбадос"),
    "BD": Country("BGD", "Bangladesh", "Бангладеш"),
    "BE": Country("BEL", "Belgium", "Бельгія"),
    "BF": Country("BFA", "Burkina Faso", "Буркіна-Фасо"),
    "BG": Country("BGR", "Bulgaria", "Болгарія"),
    "BH": Country("BHR", "Bahrain", "Бахрейн"),
    "BI": Country("BDI", "Burundi", "Бурунді"),
    "BJ": Country("BEN", "Benin", "Бенін"),
    "BL": Country("BLM", "Saint Barthélemy", "Сен-Бартельмі"),
    "BM": Country("BMU", "Bermuda", "Бермудські острови"),
    "BN": Country("BRN", "Brunei Darussalam", "Бруней"),
    "BO": Country("BOL", "Bolivia", "Болівія"),
    "BQ": Country(
        "BES", "Bonaire, Sint Eustatius and Saba", "Бонайре, Сінт-Естатіус і Саба"
    ),
    "BR": Country("BRA", "Brazil", "Бразилія"),
    "BS": Country("BHS", "Bahamas", "Багамські острови"),
    "BT": Country("BTN", "Bhutan", "Бутан"),
    "BV": Country("BVT", "Bouvet Island", "Острів Буве"),
    "BW": Country("BWA", "Botswana", "Ботсвана"),
    "BY": Country("BLR", "Belarus", "Білорусь"),
    "BZ": Country("BLZ", "Belize", "Беліз"),
    "CA": Country("CAN", "Canada", "Канада"),
    "CC": Country("CCK", "Cocos (Keeling) Islands", "Кокосові (Кілінг) острови"),
    "CD": Country(
        "COD", "Congo, The Democratic Republic of the", "Демократична Республіка Конго"
    ),
    "CF": Country(
        "CAF", "Central African Republic", "Центральноафриканська Республіка"
    ),
    "CG": Country("COG", "Congo", "Конго"),
    "CH": Country("CHE", "Switzerland", "Швейцарія"),
    "CI": Country("CIV", "Côte d'Ivoire", "Кот-д'Івуар"),
    "CK": Country("COK", "Cook Islands", "Острови Кука"),
    "CL": Country("CHL", "Chile", "Чилі"),
    "CM": Country("CMR", "Cameroon", "Камерун"),
    "CN": Country("CHN", "China", "Китай"),
    "CO": Country("COL", "Colombia", "Колумбія"),
    "CR": Country("CRI", "Costa Rica", "Коста-Рика"),
    "CU": Country("CUB", "Cuba", "Куба"),
    "CV": Country("CPV", "Cabo Verde", "Кабо-Верде"),
    "CW": Country("CUW", "Curaçao", "Кюрасао"),
    "CX": Country("CXR", "Christmas Island", "Острів Різдва"),
    "CY": Country("CYP", "Cyprus", "Кіпр"),
    "CZ": Country("CZE", "Czechia", "Чехія"),
    "DE": Country("DEU", "Germany", "Німеччина"),
    "DJ": Country("DJI", "Djibouti", "Джибуті"),
    "DK": Country("DNK", "Denmark", "Данія"),
    "DM": Country("DMA", "Dominica", "Домініка"),
    "DO": Country("DOM", "Dominican Republic", "Домініканська республіка"),
    "DZ": Country("DZA", "Algeria", "Алжир"),
    "EC": Country("ECU", "Ecuador", "Еквадор"),
    "EE": Country("EST", "Estonia", "Естонія"),
    "EG": Country("EGY", "Egypt", "Єгипет"),
    "EH": Country("ESH", "Western Sahara", "Західна Сахара"),
    "ER": Country("ERI", "Eritrea", "Еритрея"),
    "ES": Country("ESP", "Spain", "Іспанія"),
    "ET": Country("ETH", "Ethiopia", "Ефіопія"),
    "FI": Country("FIN", "Finland", "Фінляндія"),
    "FJ": Country("FJI", "Fiji", "Фіджі"),
    "FK": Country("FLK", "Falkland Islands (Malvinas)", "Фолклендські острови"),
    "FM": Country("FSM", "Micronesia", "Мікронезія"),
    "FO": Country("FRO", "Faroe Islands", "Фарерські острови"),
    "FR": Country("FRA", "France", "Франція"),
    "GA": Country("GAB", "Gabon", "Габон"),
    "GB": Country("GBR", "United Kingdom", "Велика Британія"),
    "GD": Country("GRD", "Grenada", "Гренада"),
    "GE": Country("GEO", "Georgia", "Грузія"),
    "GF": Country("GUF", "French Guiana", "Французька Гвіана"),
    "GG": Country("GGY", "Guernsey", "Острів Гернсі"),
    "GH": Country("GHA", "Ghana", "Гана"),
    "GI": Country("GIB", "Gibraltar", "Гібралтар"),
    "GL": Country("GRL", "Greenland", "Ґренландія"),
    "GM": Country("GMB", "Gambia", "Гамбія"),
    "GN": Country("GIN", "Guinea", "Гвінея"),
    "GP": Country("GLP", "Guadeloupe", "Гваделупа"),
    "GQ": Country("GNQ", "Equatorial Guinea", "Екваторіальна Гвінея"),
    "GR": Country("GRC", "Greece", "Греція"),
    "GS": Country(
        "SGS",
        "South Georgia and the South Sandwich Islands",
        "Південна Джорджія та Південні Сандвічеві острови",
    ),
    "GT": Country("GTM", "Guatemala", "Гватемала"),
    "GU": Country("GUM", "Guam", "Гуам"),
    "GW": Country("GNB", "Guinea-Bissau", "Гвінея-Бісау"),
    "GY": Country("GUY", "Guyana", "Гаяна"),
    "HK": Country("HKG", "Hong Kong", "Гонконг"),
    "HM": Country(
        "HMD", "Heard Island and McDonald Islands", "Острів Герд і острови Макдональд"
    ),
    "HN": Country("HND", "Honduras", "Гондурас"),
    "HR": Country("HRV", "Croatia", "Хорватія"),
    "HT": Country("HTI", "Haiti", "Гаїті"),
    "HU": Country("HUN", "Hungary", "Угорщина"),
    "ID": Country("IDN", "Indonesia", "Індонезія"),
    "IE": Country("IRL", "Ireland", "Ірландія"),
    "IL": Country("ISR", "Israel", "Ізраїль"),
    "IM": Country("IMN", "Isle of Man", "Острів Мен"),
    "IN": Country("IND", "India", "Індія"),
    "IO": Country(
        "IOT",
        "British Indian Ocean Territory",
        "Британська територія в Індійському океані",
    ),
    "IQ": Country("IRQ", "Iraq", "Ірак"),
    "IR": Country("IRN", "Iran", "Іран"),
    "IS": Country("ISL", "Iceland", "Ісландія"),
    "IT": Country("ITA", "Italy", "Італія"),
    "JE": Country("JEY", "Jersey", "Джерсі"),
    "JM": Country("JAM", "Jamaica", "Ямайка"),
    "JO": Country("JOR", "Jordan", "Йорданія"),
    "JP": Country("JPN", "Japan", "Японія"),
    "KE": Country("KEN", "Kenya", "Кенія"),
    "KG": Country("KGZ", "Kyrgyzstan", "Киргизстан"),
    "KH": Country("KHM", "Cambodia", "Камбоджа"),
    "KI": Country("KIR", "Kiribati", "Кірибаті"),
    "KM": Country("COM", "Comoros", "Коморські острови"),
    "KN": Country("KNA", "Saint Kitts and Nevis", "Сент-Кіттс і Невіс"),
    "KP": Country("PRK", "North Korea", "Північна Корея"),
    "KR": Country("KOR", "South Korea", "Південна Корея"),
    "KW": Country("KWT", "Kuwait", "Кувейт"),
    "KY": Country("CYM", "Cayman Islands", "Кайманові острови"),
    "KZ": Country("KAZ", "Kazakhstan", "Казахстан"),
    "LA": Country("LAO", "Laos", "Лаос"),
    "LB": Country("LBN", "Lebanon", "Ліван"),
    "LC": Country("LCA", "Saint Lucia", "Сент-Люсія"),
    "LI": Country("LIE", "Liechtenstein", "Ліхтенштейн"),
    "LK": Country("LKA", "Sri Lanka", "Шрі-Ланка"),
    "LR": Country("LBR", "Liberia", "Ліберія"),
    "LS": Country("LSO", "Lesotho", "Лесото"),
    "LT": Country("LTU", "Lithuania", "Литва"),
    "LU": Country("LUX", "Luxembourg", "Люксембург"),
    "LV": Country("LVA", "Latvia", "Латвія"),
    "LY": Country("LBY", "Libya", "Лівія"),
    "MA": Country("MAR", "Morocco", "Марокко"),
    "MC": Country("MCO", "Monaco", "Монако"),
    "MD": Country("MDA", "Moldova", "Молдова"),
    "ME": Country("MNE", "Montenegro", "Чорногорія"),
    "MF": Country(
        "MAF", "Saint Martin (French part)", "Сен-Мартен (французька частина)"
    ),
    "MG": Country("MDG", "Madagascar", "Мадагаскар"),
    "MH": Country("MHL", "Marshall Islands", "Маршаллові острови"),
    "MK": Country("MKD", "North Macedonia", "Північна Македонія"),
    "ML": Country("MLI", "Mali", "Малі"),
    "MM": Country("MMR", "Myanmar", "М’янма"),
    "MN": Country("MNG", "Mongolia", "Монголія"),
    "MO": Country("MAC", "Macao", "Макао"),
    "MP": Country("MNP", "Northern Mariana Islands", "Північні Маріанські Острови"),
    "MQ": Country("MTQ", "Martinique", "Мартиніка"),
    "MR": Country("MRT", "Mauritania", "Мавританія"),
    "MS": Country("MSR", "Montserrat", "Монтсеррат"),
    "MT": Country("MLT", "Malta", "Мальта"),
    "MU": Country("MUS", "Mauritius", "Маврикій"),
    "MV": Country("MDV", "Maldives", "Мальдіви"),
    "MW": Country("MWI", "Malawi", "Малаві"),
    "MX": Country("MEX", "Mexico", "Мексика"),
    "MY": Country("MYS", "Malaysia", "Малайзія"),
    "MZ": Country("MOZ", "Mozambique", "Мозамбік"),
    "NA": Country("NAM", "Namibia", "Намібія"),
    "NC": Country("NCL", "New Caledonia", "Нова Каледонія"),
    "NE": Country("NER", "Niger", "Нігер"),
    "NF": Country("NFK", "Norfolk Island", "Острів Норфолк"),
    "NG": Country("NGA", "Nigeria", "Нігерія"),
    "NI": Country("NIC", "Nicaragua", "Нікарагуа"),
    "NL": Country("NLD", "Netherlands", "Нідерланди"),
    "NO": Country("NOR", "Norway", "Норвегія"),
    "NP": Country("NPL", "Nepal", "Непал"),
    "NR": Country("NRU", "Nauru", "Науру"),
    "NU": Country("NIU", "Niue", "Ніуе"),
    "NZ": Country("NZL", "New Zealand", "Нова Зеландія"),
    "OM": Country("OMN", "Oman", "Оман"),
    "PA": Country("PAN", "Panama", "Панама"),
    "PE": Country("PER", "Peru", "Перу"),
    "PF": Country("PYF", "French Polynesia", "Французька Полінезія"),
    "PG": Country("PNG", "Papua New Guinea", "Папуа Нова Гвінея"),
    "PH": Country("PHL", "Philippines", "Філіппіни"),
    "PK": Country("PAK", "Pakistan", "Пакистан"),
    "PL": Country("POL", "Poland", "Польща"),
    "PM": Country("SPM", "Saint Pierre and Miquelon", "Сен-П'єр і Мікелон"),
    "PN": Country("PCN", "Pitcairn", "Піткерн"),
    "PR": Country("PRI", "Puerto Rico", "Пуерто-Рико"),
    "PS": Country("PSE", "Palestine", "Палестина"),
    "PT": Country("PRT", "Portugal", "Португалія"),
    "PW": Country("PLW", "Palau", "Палау"),
    "PY": Country("PRY", "Paraguay", "Парагвай"),
    "QA": Country("QAT", "Qatar", "Катар"),
    "RE": Country("REU", "Réunion", "Реюньйон"),
    "RO": Country("ROU", "Romania", "Румунія"),
    "RS": Country("SRB", "Serbia", "Сербія"),
    "RU": Country("RUS", "Russian Federation", "Російська Федерація"),
    "RW": Country("RWA", "Rwanda", "Руанда"),
    "SA": Country("SAU", "Saudi Arabia", "Саудівська Аравія"),
    "SB": Country("SLB", "Solomon Islands", "Соломонові Острови"),
    "SC": Country("SYC", "Seychelles", "Сейшели"),
    "SD": Country("SDN", "Sudan", "Судан"),
    "SE": Country("SWE", "Sweden", "Швеція"),
    "SG": Country("SGP", "Singapore", "Сінгапур"),
    "SH": Country(
        "SHN",
        "Saint Helena, Ascension and Tristan da Cunha",
        "Острови Святої Єлени, Вознесіння і Тристан-да-Кунья",
    ),
    "SI": Country("SVN", "Slovenia", "Словенія"),
    "SJ": Country("SJM", "Svalbard and Jan Mayen", "Острови Свальбард і Ян Маєн"),
    "SK": Country("SVK", "Slovakia", "Словаччина"),
    "SL": Country("SLE", "Sierra Leone", "Сьєрра-Леоне"),
    "SM": Country("SMR", "San Marino", "Сан-Марино"),
    "SN": Country("SEN", "Senegal", "Сенегал"),
    "SO": Country("SOM", "Somalia", "Сомалі"),
    "SR": Country("SUR", "Suriname", "Суринам"),
    "SS": Country("SSD", "South Sudan", "Південний Судан"),
    "ST": Country("STP", "Sao Tome and Principe", "Сан-Томе і Принсіпі"),
    "SV": Country("SLV", "El Salvador", "Сальвадор"),
    "SX": Country(
        "SXM", "Sint Maarten (Dutch part)", "Сінт-Мартен (голландська частина)"
    ),
    "SY": Country("SYR", "Syria", "Сирія"),
    "SZ": Country("SWZ", "Eswatini", "Есватіні"),
    "TC": Country("TCA", "Turks and Caicos Islands", "Острови Теркс і Кайкос"),
    "TD": Country("TCD", "Chad", "Чад"),
    "TF": Country(
        "ATF", "French Southern Territories", "Французькі Південні Території"
    ),
    "TG": Country("TGO", "Togo", "Того"),
    "TH": Country("THA", "Thailand", "Таїланд"),
    "TJ": Country("TJK", "Tajikistan", "Таджикистан"),
    "TK": Country("TKL", "Tokelau", "Токелау"),
    "TL": Country("TLS", "Timor-Leste", "Східний Тимор"),
    "TM": Country("TKM", "Turkmenistan", "Туркменістан"),
    "TN": Country("TUN", "Tunisia", "Туніс"),
    "TO": Country("TON", "Tonga", "Тонга"),
    "TR": Country("TUR", "Türkiye", "Туреччина"),
    "TT": Country("TTO", "Trinidad and Tobago", "Тринідад і Тобаго"),
    "TV": Country("TUV", "Tuvalu", "Тувалу"),
    "TW": Country("TWN", "Taiwan", "Тайвань"),
    "TZ": Country("TZA", "Tanzania", "Танзанія"),
    "UA": Country("UKR", "Ukraine", "Україна"),
    "UG": Country("UGA", "Uganda", "Уганда"),
    "UM": Country(
        "UMI", "United States Minor Outlying Islands", "Зовнішні малі острови США"
    ),
    "US": Country("USA", "United States", "США"),
    "UY": Country("URY", "Uruguay", "Уругвай"),
    "UZ": Country("UZB", "Uzbekistan", "Узбекистан"),
    "VA": Country("VAT", "Vatican City", "Ватикан"),
    "VC": Country(
        "VCT", "Saint Vincent and the Grenadines", "Сент-Вінсент і Гренадини"
    ),
    "VE": Country("VEN", "Venezuela", "Венесуела"),
    "VG": Country("VGB", "Virgin Islands, British", "Віргінські острови (Британія)"),
    "VI": Country("VIR", "Virgin Islands, U.S.", "Віргінські острови (США)"),
    "VN": Country("VNM", "Vietnam", "В'єтнам"),
    "VU": Country("VUT", "Vanuatu", "Вануату"),
    "WF": Country("WLF", "Wallis and Futuna", "Волліс і Футуна"),
    "WS": Country("WSM", "Samoa", "Самоа"),
    "YE": Country("YEM", "Yemen", "Ємен"),
    "YT": Country("MYT", "Mayotte", "Майотта"),
    "ZA": Country("ZAF", "South Africa", "Південна Африка"),
    "ZM": Country("ZMB", "Zambia", "Замбія"),
    "ZW": Country("ZWE", "Zimbabwe", "Зімбабве"),
}


def country_name(code: str, language: str | None) -> str:
    """Country name in the given language, English otherwise."""
    country = COUNTRIES[code]
    return country.uk if (language or "").startswith("uk") else country.en
